### ISSUE TITLE
Identify polyA intervals (pAi) from a given genome

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/polyA#1]

**Comment by mplass** [comment]
I'll upload this.

**Comment by mschilli87** [comment]
As a Python 3 function? ;)

**Comment by mplass** [comment]
well,
I will upload firs a functional perl5 script (that is what I have with a 
minor bug) and then we get the python.
Don't challenge me ;)

**Comment by nukappa** [comment]
but why not directly in python?

i thought we agreed yesterday that we will use python...

**Comment by mplass** [comment]
sure.
then just python. it will just take a bit longer...

**Comment by nukappa** [comment]
is ok, we won't be submitting next week :)
