### ISSUE TITLE
Extract 3' UTR information from a given gtf 

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/polyA#2]

**Comment by mschilli87** [comment]
I can do this.

Let's define what exactly we need:
- gene/transcript ID?
- contig
- start (let's say 0-based inclusive?)
- end (let's say 0-based exclusive?)
- strand

Anything else?

If not, I guess we aim for a GTF2BED tool?
It'll take me some minutes in `R` or longer in `Python`.

So once it's decided if this can be some kind of pre-processing stand-alone command line tool (the UNIX way) or we want everything to be integrated in one big `Python` library (less prerequisites, better portability?), I will start coding that part.

**Comment by mplass** [comment]
I already have a script that does that... in perl :D

**Comment by mrdrgz** [comment]
I can write that in python relatively clean and fast :)

**Comment by mschilli87** [comment]
Why don't you stop spamming and pick another issue to work on or unwatch this repo if you don't want to contibute/get spammed? ;)

@nukappa: I'll do it as Python 3 function as discussed. Also I'll avoid external packages were possible to make this thing as self-contained as possible.

**Comment by mplass** [comment]
Hey @mschilli87  about the coordinates, if it's a bed file I think the best is follow the standards (half open 0 based), that' what you meant?

**Comment by mschilli87** [comment]
yes: 0-based, half open (i.e. start inclusive, end exclusive)

**Comment by marvin-jens** [comment]
Some of my code could help there. I have a factory function

transcripts_from_gtf(gtf_file)

over which you can iterate. Then, each record will have a UTR3
attribute, which is an ExonChain object that can (for example) convert
coordinates, etc.

from byo.gene_model import *

for tx in transcripts_from_GTF(gtf_file):
  if tx.UTR3:
     utr = tx.UTR3
     spliced_coord = utr.map_block_to_spliced(pA_cluster.start,
pA_cluster.end)

Perhaps that would be helpful.

Best,
    -Marvin

On 04/15/2016 11:37 AM, mplass wrote:

> Hey @mschilli87 https://github.com/mschilli87 about the coordinates,
> if it's a bed file I think the best is follow the standards (half open
> 0 based), that' what you meant?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/rajewsky-lab/polyA/issues/2#issuecomment-210385311

## 

Dr. Marvin Jens

  Systems Biology of Gene Regulatory Elements (Nikolaus Rajewsky lab)
  Max Delbrück Center for Molecular Medicine
  Robert-Rössle Str. 10 (H. 87)
  13092 Berlin, Germany

  Phone: +49 30 9406 2989

**Comment by mschilli87** [comment]
this should have been closed instead of #6 ;)
