### ISSUE TITLE
discretization of bioanalyzer needs debugging

### ISSUE THREAD

**Issue by nukappa** [rajewsky-lab/polyA#49]

**Comment by nukappa** [comment]
ok i corrected this one in a pushed commit. 
i rewrote the function by using SciPy's `interp1d` function. It now works fine regardless of the `bin_size`.

**Comment by mschilli87** [comment]
Shall I test & merge #48 then or are you still adding commits to this one?

**Comment by nukappa** [comment]
yes, test & merge please...
